### ISSUE TITLE
Crashes upon opening

### ISSUE THREAD

**Issue by laughablelife** [tokaido/tokaidoapp#76]
Won't stay open long enough for me to even run the code, crashes every time it's opened.

**Comment by androbtech** [comment]
@laughablelife It's fixed on master. We haven't released it yet. @wycats

**Comment by craftified** [comment]
any ETA for release?

**Comment by androbtech** [comment]
@craftified Very soon. I will notify you.

**Comment by androbtech** [comment]
Tokaido v2.1 (Ruby 2.1.5-p273) has been released. Please [download here](https://github.com/tokaido/tokaidoapp/releases/tag/v2.1).

We'll be releasing another one very soon too (for Ruby > 2.2.0). It shouldn't be a problem once you start using the next one since the change only deals with the Ruby version.

If you hit issues, please file bugs. I'll leave this open until we do next release.

/cc @laughablelife @craftified @wagenet @wycats

**Comment by androbtech** [comment]
We've done three releases for Ruby 2.1.5, 2.1.6, and 2.2.2. 

The Ruby version is a direct 1-1 mapping with the Tokaido version release. We did a 2.1.5 release before but this one includes a few UI bug fixes and it's codenamed "Goat"

[Releases are here](https://github.com/tokaido/tokaidoapp/releases). /cc @laughablelife @craftified @wagenet @wycats
