### ISSUE TITLE
Latest Ruby 2.2?

### ISSUE THREAD

**Issue by amHammock** [tokaido/tokaidoapp#79]
According to this article on using Tokaido:  http://www.sitepoint.com/tokaido-quick-start-rails/

Tokaido should install Ruby 2.2.  I just installed Tokaido (on OSX 10.9.5) and in the Tokaido terminal window I get:

$ rails -v
Rails 4.2.0
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin12.0]

Since I'm starting a brand new Rails project I'd like to use the latest everything, how do I update Ruby with Tokaido?  Is this a potential issue since Tokaido is supposed to get the latest stable version to begin with?

Sorry for using this as a discussion forum but there is so little doc out there on how to use this app. Little or no chatter on StackOverflow either. Love the app and wanna see the docs and usage info get up to speed

**Comment by androbtech** [comment]
Hi @amHammock, thanks for trying Tokaido.

The latest Tokaido will install Ruby version 2.1.5 as the prompt reported. We expect to release the next version that bundles Ruby 2.2 before or during Railsconf.

Fortunately, you don't need the latest Ruby version to get up to speed with your brand new Rails app. Depending on your experience with Ruby perhaps it'd be better if you stick with this version until we ship next Tokaido. 

Once we ship next Tokaido you will only need to download, and run it and the newer Ruby will be used with your existing Rails project.

Again, depending on your experience. Updating the Ruby right now might consume a lot of your time since we don't provide facilities for doing so manually, yet. Best bet is to wait until end of this month and provide feedback on how the update goes (this would be very useful for us)

You'd need to download the Xcode Command Line tools, libraries needed by Ruby, the Ruby source code, compile the Ruby, and then set the paths appropriately to start using it.

Please file as many feature requests tickets. I'd be happy to work on these and make Tokaido a better experience for our users.

**Comment by amHammock** [comment]
k. Makes sense, I'm good w/Ruby 2.1.5 for now.  Will report back any issues as I get this new app going.  Been using Rails on & off since v2.2 so I'm trying to start the new app as a Rails 4 newbie to pick up all the new conventions from the get-go instead of retro-fitting an existing app.

Thanks for all of your work on this, great addition to the Ruby/Rails ecosystem!

**Comment by androbtech** [comment]
Thank you @amHammock. You shouldn't experience issues using this Ruby version. Only [Rails 5.0](http://weblog.rubyonrails.org/2014/12/19/Rails-4-2-final/) will work exclusively with Ruby 2.2 

Still, we will ship the next Tokaido with Ruby 2.2.

The reason we didn't release Ruby 2.2 since it came out was that it would've been problematic for most users trying to install and run Discourse.

**Comment by androbtech** [comment]
@amHammock Please read (Rails 4.2 Guides)[http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html] section 1.2 Ruby Versions

**Comment by androbtech** [comment]
@amHammock I'm closing this. We did three releases yesterday (including Ruby 2.2.2). Let me know how the update goes. [Release are here](https://github.com/tokaido/tokaidoapp/releases).
